<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LdcContentBlock\ContentBlockService'                     => __DIR__ . '/src/ContentBlockService.php',
  'LdcContentBlock\ContentBlockViewHelperFactory'           => __DIR__ . '/src/ContentBlockViewHelperFactory.php',
  'LdcContentBlock\ContentBlockViewHelper'                  => __DIR__ . '/src/ContentBlockViewHelper.php',
  'LdcContentBlock\ContentBlockServiceFactory'              => __DIR__ . '/src/ContentBlockServiceFactory.php',
  'LdcContentBlock\ContentBlockManagerFactory'              => __DIR__ . '/src/ContentBlockManagerFactory.php',
  'LdcContentBlock\Options\ModuleOptionsFactory'            => __DIR__ . '/src/Options/ModuleOptionsFactory.php',
  'LdcContentBlock\Options\ModuleOptions'                   => __DIR__ . '/src/Options/ModuleOptions.php',
  'LdcContentBlock\ContentBlockManager'                     => __DIR__ . '/src/ContentBlockManager.php',
  'LdcContentBlock\Exception\ContentBlockNotFoundException' => __DIR__ . '/src/Exception/ContentBlockNotFoundException.php',
  'LdcContentBlock\Exception\InvalidContentBlockException'  => __DIR__ . '/src/Exception/InvalidContentBlockException.php',
);
